version: '3.8'

services:
  django-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    env_file:
      - backend/.env
    ports:
      - '8000:8000'

  react-app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/usr/share/nginx/html


  nginx:
    image: nginx:alpine
    ports:
      - '8081:8081'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend/media:/app/media
      - ./backend/static:/app/static
      - /etc/ssl:/etc/ssl:ro




