# Generated by Django 4.2.2 on 2023-06-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_cartproduct_cart_products_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
