# Generated by Django 4.2.2 on 2023-07-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
