# Generated by Django 4.2.2 on 2023-07-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
